language: java

services:
  - docker

notifications:
  email:
    recipients:
      - adamklemanovits@gmail.com
    on_success: never

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean package docker:build