spring:
  h2:
    console:
      enable: true

security:
  basic:
    enable: false

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

server:
  port: 9191
  contextPath: /uaa